# Generated by Django 6.0.5 on 2026-06-04 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_donation_donor_email_donation_donor_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('annual', 'Annual Report'), ('program', 'Program Report'), ('financial', 'Financial Statement'), ('research', 'Research / Study'), ('other', 'Other')], default='annual', max_length=20)),
                ('year', models.PositiveIntegerField(help_text='Year this report covers e.g. 2024')),
                ('description', models.TextField(blank=True, help_text='Short summary shown on the reports listing page')),
                ('cover_image', models.ImageField(blank=True, help_text='Optional cover thumbnail', null=True, upload_to='reports/covers/')),
                ('file', models.FileField(help_text='Upload the PDF report', upload_to='reports/files/')),
                ('file_size_kb', models.PositiveIntegerField(default=0, editable=False, help_text='Auto-calculated on save')),
                ('pages', models.PositiveIntegerField(blank=True, default=0, help_text='Number of pages (optional)')),
                ('is_published', models.BooleanField(default=True)),
                ('downloads', models.PositiveIntegerField(default=0, editable=False, help_text='Auto-incremented on each download')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Impact Report',
                'verbose_name_plural': 'Impact Reports',
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=60)),
                ('source', models.CharField(choices=[('homepage', 'Homepage Footer'), ('popup', 'Exit-Intent Popup'), ('contact', 'Contact Page'), ('volunteer', 'Volunteer Page'), ('manual', 'Manually Added')], default='homepage', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('unsubscribe_token', models.CharField(blank=True, max_length=64, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.AddField(
            model_name='program',
            name='full_body',
            field=models.TextField(blank=True, help_text='Full program description'),
        ),
        migrations.AddField(
            model_name='program',
            name='icon',
            field=models.CharField(blank=True, help_text='Font Awesome class', max_length=60),
        ),
        migrations.AddField(
            model_name='program',
            name='stat_1_label',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='program',
            name='stat_1_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='program',
            name='stat_2_label',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='program',
            name='stat_2_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='program',
            name='stat_3_label',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='program',
            name='stat_3_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='donation',
            name='receipt_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProgramGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='programs/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='website.program')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('skills', models.TextField()),
                ('motivation', models.TextField()),
                ('availability', models.CharField(choices=[('weekdays', 'Weekdays (Mon–Fri)'), ('weekends', 'Weekends (Sat–Sun)'), ('evenings', 'Evenings only'), ('flexible', 'Flexible / Remote')], default='weekends', max_length=20)),
                ('commitment', models.CharField(choices=[('once_off', 'Once-off event'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('long_term', 'Long-term (6+ months)')], default='monthly', max_length=20)),
                ('has_experience', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('shortlisted', 'Shortlisted'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteers', to='website.program')),
            ],
            options={
                'verbose_name': 'Volunteer Application',
                'verbose_name_plural': 'Volunteer Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
